### ISSUE TITLE
ubuntu22.04下 后端生成迁移脚本报错

### ISSUE THREAD

**Issue by zenner3000** [FuAdmin/fu-fastapi-vue#1]
环境：Ubuntu 22.04 ， Python 3.10.12

后端到这一步骤 报错
```
alembic revision --autogenerate -m "initial migration"
```

报错信息如下
```
$ alembic revision --autogenerate -m "initial migration"
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'sys_user'
INFO  [alembic.autogenerate.compare] Detected added index ''ix_sys_user_email'' on '('email',)'
INFO  [alembic.autogenerate.compare] Detected added index ''ix_sys_user_mobile'' on '('mobile',)'
INFO  [alembic.autogenerate.compare] Detected added index ''ix_sys_user_username'' on '('username',)'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_dept'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_dict'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_file'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_log_login'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_log_operation'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_menu'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_post'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_role'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_button'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_dict_item'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_role_menu'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_user_post'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_user_role'
INFO  [alembic.autogenerate.compare] Detected added table 'sys_role_button'
  Generating /home/god/Desktop/py_project/fu-fastapi-
  vue/backend/alembic/versions/914682da3201_initial_migration.py ...  FAILED
Traceback (most recent call last):
  File "/home/god/.local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/god/.local/lib/python3.10/site-packages/alembic/config.py", line 636, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/god/.local/lib/python3.10/site-packages/alembic/config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "/home/god/.local/lib/python3.10/site-packages/alembic/config.py", line 603, in run_cmd
    fn(
  File "/home/god/.local/lib/python3.10/site-packages/alembic/command.py", line 243, in revision
    scripts = [script for script in revision_context.generate_scripts()]
  File "/home/god/.local/lib/python3.10/site-packages/alembic/command.py", line 243, in <listcomp>
    scripts = [script for script in revision_context.generate_scripts()]
  File "/home/god/.local/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 650, in generate_scripts
    yield self._to_script(generated_revision)
  File "/home/god/.local/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 555, in _to_script
    return self.script_directory.generate_revision(
  File "/home/god/.local/lib/python3.10/site-packages/alembic/script/base.py", line 747, in generate_revision
    self._generate_template(
  File "/home/god/.local/lib/python3.10/site-packages/alembic/script/base.py", line 592, in _generate_template
    util.template_to_file(src, dest, self.output_encoding, **kw)
  File "/home/god/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 41, in template_to_file
    with open(dest, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/god/Desktop/py_project/fu-fastapi-vue/backend/alembic/versions/914682da3201_initial_migration.py
```

根据报错信息，是  /home/god/Desktop/py_project/fu-fastapi-
  vue/backend/alembic/versions/914682da3201_initial_migration.py 这里， 生成这个文件失败

**Comment by FuAdmin** [comment]
在alembic 下 手动创建一个versions文件夹
